"""Bootstrap foundation: control, registry and provenance schema.

Revision ID: 0001_bootstrap
Revises:
Create Date: 2026-09-17 16:33:13.848234

This is the authoritative RES-96 bootstrap revision for the DynamisData
PostgreSQL control plane. It creates 25 tables in the configured schema
(``DYNAMIS_DB_SCHEMA``, default ``dynamis``):

* rights and registry: ``license_policy``, ``dataset_source``,
  ``dataset_source_modality``, ``dataset_version``, ``dataset_version_file``;
* scientific structure: ``subject``, ``protocol``, ``session``,
  ``session_participant``, ``trial``, ``device``, ``sensor_stream``;
* first-class support authorities: ``clock``, ``coordinate_frame``,
  ``frame_transform``, ``synchronization_spec``, ``skeleton_definition``,
  ``skeleton_joint``, ``sample_artifact``;
* processing and provenance: ``algorithm_spec``, ``processing_run``,
  ``processing_artifact``, ``quality_issue``, ``metric_definition``,
  ``derived_metric``.

Deliberate design decisions encoded in the DDL:

* ``session`` carries no ``subject_id``: a match or team session holds many
  participants through ``session_participant``, so one match identity is never
  duplicated per player;
* ``algorithm_spec`` and ``metric_definition`` are global scientific
  definitions, not artifacts owned by one dataset;
* dense samples never enter PostgreSQL: only artifact metadata is stored, and
  ``sample_artifact`` enforces Parquet+Zstd when the format is Parquet;
* ``processing_run`` and ``derived_metric`` require non-empty
  ``input_checksums``, so a derived value cannot exist without its inputs;
* ``quality_issue`` requires non-empty evidence;
* ``frame_transform`` requires an ``algorithm_id`` or written ``notes``, so no
  coordinate transform can be implicit.

Invariants that need a subquery (minimum participant counts, declared parent
frames requiring a transform) live in ``dynamis.contracts.invariants`` and are
enforced by the frozen Pydantic contracts.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_bootstrap"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "algorithm_spec",
        sa.Column("algorithm_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("code_git_sha", sa.String(length=40), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("parameters_hash", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('adapter', 'canonicalizer', 'qc_rule', 'processor', 'metric', 'exporter')",
            name=op.f("ck_algorithm_spec_kind"),
        ),
        sa.CheckConstraint(
            "parameters = '{}'::jsonb OR parameters_hash IS NOT NULL",
            name=op.f("ck_algorithm_spec_parameters_need_hash"),
        ),
        sa.PrimaryKeyConstraint("algorithm_id", name=op.f("pk_algorithm_spec")),
        sa.UniqueConstraint("name", "version", name="uq_algorithm_spec_name_version"),
    )
    op.create_table(
        "clock",
        sa.Column("clock_id", sa.String(length=128), nullable=False),
        sa.Column("timebase", sa.String(length=32), nullable=False),
        sa.Column("frequency_hz", sa.Float(), nullable=True),
        sa.Column("epoch_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("drift_ppm", sa.Float(), nullable=True),
        sa.Column("rollover_period_s", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "timebase IN ('utc', 'gnss_utc', 'device_monotonic', 'session_monotonic', 'gps_week_time', 'unknown')",
            name=op.f("ck_clock_timebase"),
        ),
        sa.CheckConstraint(
            "timebase NOT IN ('device_monotonic', 'session_monotonic') OR epoch_utc IS NULL",
            name=op.f("ck_clock_monotonic_has_no_epoch"),
        ),
        sa.CheckConstraint(
            "frequency_hz IS NULL OR frequency_hz > 0", name=op.f("ck_clock_positive_frequency")
        ),
        sa.PrimaryKeyConstraint("clock_id", name=op.f("pk_clock")),
    )
    op.create_table(
        "coordinate_frame",
        sa.Column("frame_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("handedness", sa.String(length=8), nullable=False),
        sa.Column("x_direction", sa.String(length=32), nullable=False),
        sa.Column("y_direction", sa.String(length=32), nullable=False),
        sa.Column("z_direction", sa.String(length=32), nullable=False),
        sa.Column("origin_description", sa.Text(), nullable=False),
        sa.Column(
            "length_unit", sa.String(length=16), server_default=sa.text("'m'"), nullable=False
        ),
        sa.Column("parent_frame_id", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "handedness IN ('right', 'left')", name=op.f("ck_coordinate_frame_handedness")
        ),
        sa.CheckConstraint(
            "kind <> 'unknown' OR description IS NOT NULL",
            name=op.f("ck_coordinate_frame_unknown_needs_description"),
        ),
        sa.CheckConstraint(
            "kind IN ('world_geodetic', 'local_enu', 'pitch', 'body', 'sensor', 'camera', 'laboratory', 'joint_local', 'unknown')",
            name=op.f("ck_coordinate_frame_kind"),
        ),
        sa.CheckConstraint(
            "parent_frame_id IS NULL OR parent_frame_id <> frame_id",
            name=op.f("ck_coordinate_frame_no_self_parent"),
        ),
        sa.CheckConstraint(
            "x_direction <> y_direction AND x_direction <> z_direction AND y_direction <> z_direction",
            name=op.f("ck_coordinate_frame_distinct_axes"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_frame_id"],
            ["coordinate_frame.frame_id"],
            name=op.f("fk_coordinate_frame_parent_frame_id_coordinate_frame"),
        ),
        sa.PrimaryKeyConstraint("frame_id", name=op.f("pk_coordinate_frame")),
    )
    op.create_table(
        "license_policy",
        sa.Column("policy_id", sa.String(length=40), nullable=False),
        sa.Column("identifier", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("noncommercial_only", sa.Boolean(), nullable=False),
        sa.Column("share_alike", sa.Boolean(), nullable=False),
        sa.Column("redistribution", sa.String(length=16), nullable=False),
        sa.Column("local_only", sa.Boolean(), nullable=False),
        sa.Column(
            "restrictions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT local_only OR redistribution = 'prohibited'",
            name=op.f("ck_license_policy_local_only_prohibits_redistribution"),
        ),
        sa.CheckConstraint(
            "identifier IS NULL OR identifier NOT LIKE '%%NC%%' OR noncommercial_only",
            name=op.f("ck_license_policy_nc_needs_noncommercial"),
        ),
        sa.CheckConstraint(
            "identifier IS NULL OR identifier NOT LIKE '%%SA%%' OR share_alike",
            name=op.f("ck_license_policy_sa_needs_share_alike"),
        ),
        sa.CheckConstraint(
            "redistribution IN ('conditional', 'prohibited')",
            name=op.f("ck_license_policy_redistribution"),
        ),
        sa.CheckConstraint(
            "status = 'declared' OR (identifier IS NULL AND local_only)",
            name=op.f("ck_license_policy_unclear_is_local_only"),
        ),
        sa.CheckConstraint(
            "status = 'unclear' OR identifier IS NOT NULL",
            name=op.f("ck_license_policy_declared_needs_identifier"),
        ),
        sa.CheckConstraint(
            "status IN ('declared', 'unclear')", name=op.f("ck_license_policy_status")
        ),
        sa.PrimaryKeyConstraint("policy_id", name=op.f("pk_license_policy")),
    )
    op.create_table(
        "protocol",
        sa.Column("protocol_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("protocol_id", name=op.f("pk_protocol")),
    )
    op.create_table(
        "skeleton_definition",
        sa.Column("skeleton_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("joint_count", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "joint_count > 0", name=op.f("ck_skeleton_definition_positive_joint_count")
        ),
        sa.PrimaryKeyConstraint("skeleton_id", name=op.f("pk_skeleton_definition")),
    )
    op.create_table(
        "dataset_source",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("upstream_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("doi", sa.String(length=160), nullable=True),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("adapter_id", sa.String(length=128), nullable=False),
        sa.Column("v1_role", sa.Text(), nullable=False),
        sa.Column("initial_scope", sa.Text(), nullable=False),
        sa.Column("license_policy_id", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "jsonb_array_length(upstream_urls) > 0", name=op.f("ck_dataset_source_has_upstream_url")
        ),
        sa.ForeignKeyConstraint(
            ["license_policy_id"],
            ["license_policy.policy_id"],
            name=op.f("fk_dataset_source_license_policy_id_license_policy"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", name=op.f("pk_dataset_source")),
    )
    op.create_table(
        "frame_transform",
        sa.Column("transform_id", sa.String(length=128), nullable=False),
        sa.Column("source_frame_id", sa.String(length=128), nullable=False),
        sa.Column("target_frame_id", sa.String(length=128), nullable=False),
        sa.Column("translation_x_m", sa.Float(), nullable=False),
        sa.Column("translation_y_m", sa.Float(), nullable=False),
        sa.Column("translation_z_m", sa.Float(), nullable=False),
        sa.Column("rotation_x", sa.Float(), nullable=False),
        sa.Column("rotation_y", sa.Float(), nullable=False),
        sa.Column("rotation_z", sa.Float(), nullable=False),
        sa.Column("rotation_w", sa.Float(), nullable=False),
        sa.Column("algorithm_id", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "algorithm_id IS NOT NULL OR notes IS NOT NULL",
            name=op.f("ck_frame_transform_explained_transform"),
        ),
        sa.CheckConstraint(
            "source_frame_id <> target_frame_id",
            name=op.f("ck_frame_transform_not_self_referential"),
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_id"],
            ["algorithm_spec.algorithm_id"],
            name=op.f("fk_frame_transform_algorithm_id_algorithm_spec"),
        ),
        sa.ForeignKeyConstraint(
            ["source_frame_id"],
            ["coordinate_frame.frame_id"],
            name=op.f("fk_frame_transform_source_frame_id_coordinate_frame"),
        ),
        sa.ForeignKeyConstraint(
            ["target_frame_id"],
            ["coordinate_frame.frame_id"],
            name=op.f("fk_frame_transform_target_frame_id_coordinate_frame"),
        ),
        sa.PrimaryKeyConstraint("transform_id", name=op.f("pk_frame_transform")),
        sa.UniqueConstraint(
            "source_frame_id", "target_frame_id", name="uq_frame_transform_source_target"
        ),
    )
    op.create_table(
        "metric_definition",
        sa.Column("metric_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("si_unit", sa.String(length=32), nullable=False),
        sa.Column("measurement_class", sa.String(length=32), nullable=False),
        sa.Column(
            "value_kind", sa.String(length=16), server_default=sa.text("'scalar'"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("algorithm_id", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "measurement_class <> 'RAW_MEASURED'", name=op.f("ck_metric_definition_not_raw")
        ),
        sa.CheckConstraint(
            "measurement_class IN ('RAW_MEASURED', 'SOURCE_DERIVED', 'PIPELINE_DERIVED', 'MODEL_ESTIMATED')",
            name=op.f("ck_metric_definition_measurement_class"),
        ),
        sa.CheckConstraint(
            "value_kind IN ('scalar', 'series', 'categorical', 'vector')",
            name=op.f("ck_metric_definition_value_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_id"],
            ["algorithm_spec.algorithm_id"],
            name=op.f("fk_metric_definition_algorithm_id_algorithm_spec"),
        ),
        sa.PrimaryKeyConstraint("metric_id", name=op.f("pk_metric_definition")),
        sa.UniqueConstraint("name", name="uq_metric_definition_name"),
    )
    op.create_table(
        "skeleton_joint",
        sa.Column("skeleton_id", sa.String(length=128), nullable=False),
        sa.Column("joint_id", sa.Integer(), nullable=False),
        sa.Column("joint_name", sa.String(length=128), nullable=False),
        sa.Column("parent_joint_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("joint_id >= 0", name=op.f("ck_skeleton_joint_nonnegative_joint_id")),
        sa.CheckConstraint(
            "parent_joint_id IS NULL OR parent_joint_id < joint_id",
            name=op.f("ck_skeleton_joint_parent_precedes_child"),
        ),
        sa.ForeignKeyConstraint(
            ["skeleton_id", "parent_joint_id"],
            ["skeleton_joint.skeleton_id", "skeleton_joint.joint_id"],
            name=op.f("fk_skeleton_joint_skeleton_id_skeleton_joint"),
        ),
        sa.ForeignKeyConstraint(
            ["skeleton_id"],
            ["skeleton_definition.skeleton_id"],
            name=op.f("fk_skeleton_joint_skeleton_id_skeleton_definition"),
        ),
        sa.PrimaryKeyConstraint("skeleton_id", "joint_id", name=op.f("pk_skeleton_joint")),
        sa.UniqueConstraint("skeleton_id", "joint_name", name="uq_skeleton_joint_name"),
    )
    op.create_table(
        "dataset_source_modality",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "modality IN ('gnss', 'imu', 'force', 'lpt', 'tracking', 'event', 'pose')",
            name=op.f("ck_dataset_source_modality_modality"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_dataset_source_modality_dataset_id_dataset_source"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "modality", name=op.f("pk_dataset_source_modality")),
    )
    op.create_table(
        "dataset_version",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("upstream_url", sa.Text(), nullable=False),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("optional", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "retrieval_status",
            sa.String(length=16),
            server_default=sa.text("'not_fetched'"),
            nullable=False,
        ),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "retrieval_status <> 'fetched' OR retrieved_at IS NOT NULL",
            name=op.f("ck_dataset_version_fetched_needs_retrieved_at"),
        ),
        sa.CheckConstraint(
            "retrieval_status IN ('not_fetched', 'fetched', 'failed')",
            name=op.f("ck_dataset_version_retrieval_status"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_dataset_version_dataset_id_dataset_source"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "version", name=op.f("pk_dataset_version")),
    )
    op.create_table(
        "device",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=64), nullable=True),
        sa.Column("vendor", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "specs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_device_dataset_id_dataset_source"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "device_id", name=op.f("pk_device")),
    )
    op.create_table(
        "processing_run",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("algorithm_id", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("code_git_sha", sa.String(length=40), nullable=True),
        sa.Column("parameters_hash", sa.String(length=64), nullable=True),
        sa.Column("dagster_run_id", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_checksums", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status <> 'completed' OR completed_at IS NOT NULL",
            name=op.f("ck_processing_run_completed_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')", name=op.f("ck_processing_run_status")
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_processing_run_time_order"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(input_checksums) > 0",
            name=op.f("ck_processing_run_provenance_requires_inputs"),
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_id"],
            ["algorithm_spec.algorithm_id"],
            name=op.f("fk_processing_run_algorithm_id_algorithm_spec"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_processing_run_dataset_id_dataset_source"),
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_processing_run")),
    )
    op.create_table(
        "session",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column(
            "kind", sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column("protocol_id", sa.String(length=128), nullable=True),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(length=256), nullable=True),
        sa.CheckConstraint(
            "kind IN ('individual', 'team', 'match', 'laboratory', 'longitudinal', 'unknown')",
            name=op.f("ck_session_kind"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_session_time_order"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_session_dataset_id_dataset_source"),
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id"], ["protocol.protocol_id"], name=op.f("fk_session_protocol_id_protocol")
        ),
        sa.PrimaryKeyConstraint("dataset_id", "session_id", name=op.f("pk_session")),
    )
    op.create_table(
        "subject",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column(
            "sex", sa.String(length=16), server_default=sa.text("'unspecified'"), nullable=False
        ),
        sa.Column("cohort", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("sex IN ('male', 'female', 'unspecified')", name=op.f("ck_subject_sex")),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_subject_dataset_id_dataset_source"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "subject_id", name=op.f("pk_subject")),
    )
    op.create_table(
        "dataset_version_file",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("upstream_md5", sa.String(length=32), nullable=True),
        sa.Column("upstream_sha256", sa.String(length=64), nullable=True),
        sa.Column("local_sha256", sa.String(length=64), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "local_sha256 IS NULL OR retrieved_at IS NOT NULL",
            name=op.f("ck_dataset_version_file_local_checksum_needs_retrieval"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes > 0",
            name=op.f("ck_dataset_version_file_positive_size"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "version"],
            ["dataset_version.dataset_id", "dataset_version.version"],
            name=op.f("fk_dataset_version_file_dataset_id_dataset_version"),
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id", "version", "key", name=op.f("pk_dataset_version_file")
        ),
    )
    op.create_table(
        "derived_metric",
        sa.Column("derived_metric_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("metric_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=True),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("trial_id", sa.String(length=128), nullable=True),
        sa.Column("stream_id", sa.String(length=128), nullable=True),
        sa.Column("si_unit", sa.String(length=32), nullable=False),
        sa.Column("measurement_class", sa.String(length=32), nullable=False),
        sa.Column("value_num", sa.Float(), nullable=True),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_checksums", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "measurement_class <> 'RAW_MEASURED'", name=op.f("ck_derived_metric_not_raw")
        ),
        sa.CheckConstraint(
            "measurement_class IN ('RAW_MEASURED', 'SOURCE_DERIVED', 'PIPELINE_DERIVED', 'MODEL_ESTIMATED')",
            name=op.f("ck_derived_metric_measurement_class"),
        ),
        sa.CheckConstraint(
            "(value_num IS NULL) <> (value_json IS NULL)",
            name=op.f("ck_derived_metric_single_value_form"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(input_checksums) > 0",
            name=op.f("ck_derived_metric_provenance_requires_inputs"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_derived_metric_dataset_id_dataset_source"),
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metric_definition.metric_id"],
            name=op.f("fk_derived_metric_metric_id_metric_definition"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_run.run_id"],
            name=op.f("fk_derived_metric_run_id_processing_run"),
        ),
        sa.PrimaryKeyConstraint("derived_metric_id", name=op.f("pk_derived_metric")),
    )
    op.create_table(
        "processing_artifact",
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "artifact_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "layer IN ('bronze', 'silver', 'gold', 'quarantine', 'cache', 'tmp')",
            name=op.f("ck_processing_artifact_layer"),
        ),
        sa.CheckConstraint(
            "byte_size IS NULL OR byte_size > 0", name=op.f("ck_processing_artifact_positive_size")
        ),
        sa.CheckConstraint(
            "row_count IS NULL OR row_count >= 0",
            name=op.f("ck_processing_artifact_nonnegative_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_processing_artifact_dataset_id_dataset_source"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_run.run_id"],
            name=op.f("fk_processing_artifact_run_id_processing_run"),
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_processing_artifact")),
        sa.UniqueConstraint("dataset_id", "relative_path", name="uq_processing_artifact_path"),
    )
    op.create_table(
        "session_participant",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.String(length=16), server_default=sa.text("'participant'"), nullable=False
        ),
        sa.Column("group_label", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "role IN ('athlete', 'player', 'goalkeeper', 'patient', 'participant', 'operator', 'unknown')",
            name=op.f("ck_session_participant_role"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "session_id"],
            ["session.dataset_id", "session.session_id"],
            name=op.f("fk_session_participant_dataset_id_session"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "subject_id"],
            ["subject.dataset_id", "subject.subject_id"],
            name=op.f("fk_session_participant_dataset_id_subject"),
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id", "session_id", "subject_id", name=op.f("pk_session_participant")
        ),
    )
    op.create_table(
        "trial",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("trial_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=True),
        sa.Column("parent_trial_id", sa.String(length=128), nullable=True),
        sa.Column("label", sa.String(length=256), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_trial_time_order"),
        ),
        sa.CheckConstraint(
            "parent_trial_id IS NULL OR parent_trial_id <> trial_id",
            name=op.f("ck_trial_no_self_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "session_id", "parent_trial_id"],
            ["trial.dataset_id", "trial.session_id", "trial.trial_id"],
            name=op.f("fk_trial_dataset_id_trial"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "session_id"],
            ["session.dataset_id", "session.session_id"],
            name=op.f("fk_trial_dataset_id_session"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "subject_id"],
            ["subject.dataset_id", "subject.subject_id"],
            name=op.f("fk_trial_dataset_id_subject"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "session_id", "trial_id", name=op.f("pk_trial")),
    )
    op.create_table(
        "synchronization_spec",
        sa.Column("sync_spec_id", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("reference_clock_id", sa.String(length=128), nullable=False),
        sa.Column("uncertainty_ms", sa.Float(), nullable=True),
        sa.Column("residual_max_abs_ms", sa.Float(), nullable=True),
        sa.Column("residual_rms_ms", sa.Float(), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_artifact_id", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "method <> 'unknown' OR (NOT verified AND uncertainty_ms IS NULL AND residual_max_abs_ms IS NULL AND residual_rms_ms IS NULL)",
            name=op.f("ck_synchronization_spec_unknown_makes_no_claim"),
        ),
        sa.CheckConstraint(
            "method IN ('source_provided', 'hardware_synchronized', 'event_aligned', 'cross_correlation_aligned', 'software_timestamped', 'unknown')",
            name=op.f("ck_synchronization_spec_method"),
        ),
        sa.CheckConstraint(
            "COALESCE(uncertainty_ms, 0) >= 0 AND COALESCE(residual_max_abs_ms, 0) >= 0 AND COALESCE(residual_rms_ms, 0) >= 0",
            name=op.f("ck_synchronization_spec_nonnegative_uncertainty"),
        ),
        sa.CheckConstraint(
            "NOT verified OR (verified_at IS NOT NULL AND evidence_artifact_id IS NOT NULL)",
            name=op.f("ck_synchronization_spec_verified_needs_evidence"),
        ),
        sa.CheckConstraint(
            "residual_rms_ms IS NULL OR residual_max_abs_ms IS NULL OR residual_rms_ms <= residual_max_abs_ms",
            name=op.f("ck_synchronization_spec_rms_bounded_by_max"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_artifact_id"],
            ["processing_artifact.artifact_id"],
            name=op.f("fk_synchronization_spec_evidence_artifact_id_processing_artifact"),
        ),
        sa.ForeignKeyConstraint(
            ["reference_clock_id"],
            ["clock.clock_id"],
            name=op.f("fk_synchronization_spec_reference_clock_id_clock"),
        ),
        sa.PrimaryKeyConstraint("sync_spec_id", name=op.f("pk_synchronization_spec")),
    )
    op.create_table(
        "sensor_stream",
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("stream_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("trial_id", sa.String(length=128), nullable=True),
        sa.Column("subject_id", sa.String(length=128), nullable=True),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("modality", sa.String(length=16), nullable=False),
        sa.Column("measurement_class", sa.String(length=32), nullable=False),
        sa.Column("clock_id", sa.String(length=128), nullable=False),
        sa.Column("synchronization_spec_id", sa.String(length=128), nullable=False),
        sa.Column("coordinate_frame_id", sa.String(length=128), nullable=True),
        sa.Column("skeleton_id", sa.String(length=128), nullable=True),
        sa.Column("nominal_sampling_rate_hz", sa.Float(), nullable=True),
        sa.Column(
            "si_units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source_unit", sa.String(length=64), nullable=True),
        sa.Column(
            "stream_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(modality = 'pose') = (skeleton_id IS NOT NULL)",
            name=op.f("ck_sensor_stream_pose_requires_skeleton"),
        ),
        sa.CheckConstraint(
            "measurement_class IN ('RAW_MEASURED', 'SOURCE_DERIVED', 'PIPELINE_DERIVED', 'MODEL_ESTIMATED')",
            name=op.f("ck_sensor_stream_measurement_class"),
        ),
        sa.CheckConstraint(
            "modality IN ('gnss', 'imu', 'force', 'lpt', 'tracking', 'event', 'pose')",
            name=op.f("ck_sensor_stream_modality"),
        ),
        sa.CheckConstraint(
            "nominal_sampling_rate_hz IS NULL OR nominal_sampling_rate_hz > 0",
            name=op.f("ck_sensor_stream_positive_sampling_rate"),
        ),
        sa.ForeignKeyConstraint(
            ["clock_id"], ["clock.clock_id"], name=op.f("fk_sensor_stream_clock_id_clock")
        ),
        sa.ForeignKeyConstraint(
            ["coordinate_frame_id"],
            ["coordinate_frame.frame_id"],
            name=op.f("fk_sensor_stream_coordinate_frame_id_coordinate_frame"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "device_id"],
            ["device.dataset_id", "device.device_id"],
            name=op.f("fk_sensor_stream_dataset_id_device"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "session_id"],
            ["session.dataset_id", "session.session_id"],
            name=op.f("fk_sensor_stream_dataset_id_session"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "subject_id"],
            ["subject.dataset_id", "subject.subject_id"],
            name=op.f("fk_sensor_stream_dataset_id_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["skeleton_id"],
            ["skeleton_definition.skeleton_id"],
            name=op.f("fk_sensor_stream_skeleton_id_skeleton_definition"),
        ),
        sa.ForeignKeyConstraint(
            ["synchronization_spec_id"],
            ["synchronization_spec.sync_spec_id"],
            name=op.f("fk_sensor_stream_synchronization_spec_id_synchronization_spec"),
        ),
        sa.PrimaryKeyConstraint("dataset_id", "stream_id", name=op.f("pk_sensor_stream")),
    )
    op.create_table(
        "quality_issue",
        sa.Column("issue_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("stream_id", sa.String(length=128), nullable=True),
        sa.Column("subject_id", sa.String(length=128), nullable=True),
        sa.Column("trial_id", sa.String(length=128), nullable=True),
        sa.Column("sample_index", sa.BigInteger(), nullable=True),
        sa.Column("rule", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'QUARANTINED'"), nullable=False
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "evidence <> '{}'::jsonb", name=op.f("ck_quality_issue_evidence_required")
        ),
        sa.CheckConstraint(
            "severity <> 'INFO' OR state <> 'QUARANTINED'",
            name=op.f("ck_quality_issue_info_is_not_quarantined"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'WARNING', 'ERROR')", name=op.f("ck_quality_issue_severity")
        ),
        sa.CheckConstraint(
            "state <> 'QUARANTINED' OR stream_id IS NOT NULL OR sample_index IS NOT NULL",
            name=op.f("ck_quality_issue_quarantine_is_located"),
        ),
        sa.CheckConstraint(
            "state IN ('VALID', 'QUARANTINED')", name=op.f("ck_quality_issue_state")
        ),
        sa.CheckConstraint(
            "sample_index IS NULL OR sample_index >= 0",
            name=op.f("ck_quality_issue_nonnegative_sample_index"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "stream_id"],
            ["sensor_stream.dataset_id", "sensor_stream.stream_id"],
            name=op.f("fk_quality_issue_dataset_id_sensor_stream"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_source.dataset_id"],
            name=op.f("fk_quality_issue_dataset_id_dataset_source"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["processing_run.run_id"],
            name=op.f("fk_quality_issue_run_id_processing_run"),
        ),
        sa.PrimaryKeyConstraint("issue_id", name=op.f("pk_quality_issue")),
    )
    op.create_table(
        "sample_artifact",
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("stream_id", sa.String(length=128), nullable=False),
        sa.Column("layer", sa.String(length=16), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column(
            "format", sa.String(length=16), server_default=sa.text("'parquet'"), nullable=False
        ),
        sa.Column(
            "compression", sa.String(length=16), server_default=sa.text("'zstd'"), nullable=False
        ),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("schema_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "partition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("coordinate_frame_id", sa.String(length=128), nullable=True),
        sa.Column("synchronization_spec_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "compression IN ('none', 'zstd', 'snappy')", name=op.f("ck_sample_artifact_compression")
        ),
        sa.CheckConstraint(
            "format <> 'parquet' OR compression = 'zstd'",
            name=op.f("ck_sample_artifact_parquet_is_zstd"),
        ),
        sa.CheckConstraint(
            "format IN ('parquet', 'arrow_ipc', 'json', 'csv', 'text', 'native')",
            name=op.f("ck_sample_artifact_format"),
        ),
        sa.CheckConstraint(
            "layer IN ('bronze', 'silver', 'gold', 'quarantine', 'cache', 'tmp')",
            name=op.f("ck_sample_artifact_layer"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_sample_artifact_positive_size")),
        sa.CheckConstraint("row_count >= 0", name=op.f("ck_sample_artifact_nonnegative_rows")),
        sa.ForeignKeyConstraint(
            ["coordinate_frame_id"],
            ["coordinate_frame.frame_id"],
            name=op.f("fk_sample_artifact_coordinate_frame_id_coordinate_frame"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "stream_id"],
            ["sensor_stream.dataset_id", "sensor_stream.stream_id"],
            name=op.f("fk_sample_artifact_dataset_id_sensor_stream"),
        ),
        sa.ForeignKeyConstraint(
            ["synchronization_spec_id"],
            ["synchronization_spec.sync_spec_id"],
            name=op.f("fk_sample_artifact_synchronization_spec_id_synchronization_spec"),
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_sample_artifact")),
        sa.UniqueConstraint("dataset_id", "relative_path", name="uq_sample_artifact_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sample_artifact")
    op.drop_table("quality_issue")
    op.drop_table("sensor_stream")
    op.drop_table("synchronization_spec")
    op.drop_table("trial")
    op.drop_table("session_participant")
    op.drop_table("processing_artifact")
    op.drop_table("derived_metric")
    op.drop_table("dataset_version_file")
    op.drop_table("subject")
    op.drop_table("session")
    op.drop_table("processing_run")
    op.drop_table("device")
    op.drop_table("dataset_version")
    op.drop_table("dataset_source_modality")
    op.drop_table("skeleton_joint")
    op.drop_table("metric_definition")
    op.drop_table("frame_transform")
    op.drop_table("dataset_source")
    op.drop_table("skeleton_definition")
    op.drop_table("protocol")
    op.drop_table("license_policy")
    op.drop_table("coordinate_frame")
    op.drop_table("clock")
    op.drop_table("algorithm_spec")
    # ### end Alembic commands ###
